<!doctype html>
<html lang="en">
<head>
    <title>Login</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<#include "header.ftlh"/>
<main style="padding-top: 6rem">
    <div class="col-3 mx-auto">
        <form method="post">
        <div class="form-group">
            <label for="">Email</label>
            <input type="email" class="form-control" name="email" id="email" placeholder="">
        </div>
        <div class="form-group">
            <label for="">Пароль</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="">
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input type="checkbox" class="form-check-input" name="remember-me" id="remember-me" value="true"
                       checked>
                Remember me
            </label>
        </div>
        <br>
        <button type="submit" class="btn btn-dark mx-auto">Войти</button>
        <br>

        <br>
        <small class="form-text text-muted"><a href="/register">Зарегистрироваться</a></small>
    </form>
        <div class="or-container">
            <br>
            <div class="line-separator"></div>
            <br>
        </div>
        <div class="row mx-auto">
            <form class="mx-auto" method="post" action="/signin/facebook">
                <input type="hidden" name="scope" value="public_profile" />
                <button type="submit" class="btn btn-light mx-auto">
                    <img src="https://img.icons8.com/ios-filled/20/000000/facebook-new.png"/>  SignIn Using Facebook
                </button>
            </form>
        </div>
    </div>
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
<style>
    .line-separator {
        background-color: #ccc;
        flex-grow: 5;
        height: 1px
    }
</style>
</html>